version: "3.9"
services:
  training:
    image: ghcr.io/vatger/training:latest
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    ports:
      - "8016:8016/tcp"
    environment:
      - CORE_API
      - T1_MIN_MINUTES
      - VATGER_API_KEY
      - GDPR_KEY
      - OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET
      - OAUTH_TOKEN_URL
      - OAUTH_AUTH_URL
      - OAUTH_REDIRECT_URL
      - OAUTH_API_URL
      - SECRET_KEY
      - ALLOWED_HOSTS
      - CSRF_TRUSTED_ORIGINS

    labels:
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - training_data:/opt/training/training/db

volumes:
  training_data: